version: '3.8'

services:
  hub-dokploy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hub-dokploy
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /etc/dokploy/traefik/dynamic:/etc/dokploy/traefik/dynamic:ro
    environment:
      - PORT=8080
      - DYNAMIC_CONFIG_DIR=/etc/dokploy/traefik/dynamic
